### PR TITLE
Fix/header multi page

### PR DESCRIPTION
**Pull request by dorianim**
Before:
image

After:
image

### CODE REVIEW

**Review by lamorak13 — CHANGES_REQUESTED** [review]
I would make the padding top of the body based on the exact pixel value of the height of the header instead of a rem value, since thei are dependent on root font-size

**Comment by dorianim** [comment]
I checked all components of the header that influence the height (paddings, margins, font size, etc.). Thei are all defined by rem and add up that value. So I thought it makes more sense to also use rem for the padding, since the header itself is also dependent on the font size.

**Comment by lamorak13** [comment]
> 

Since the padding and font-size are all set in pixel, I think it would be more consistent with the current css that we have written so far. 
Although there is a discussion to be had whether we want to change sizes to use em/rem instead of pixel.

**Comment by dorianim** [comment]
Padding and font sizes are not set in pixels. They are all set in rem:
image (nav)

image
image
(ul)

-> Add it all up:
```
0.625 (nav top)
1.000 (ul top)
1.500 (ul line-height)
1.000 (up bottom)
0.625 (nav bottom)
-----
4.750
```

You can also see that by adding a css rule like
```css
html {
  font-size: 30px;
}
```
All the sizes increase, also the pixel size of the header. We have to use rem.

**Comment by lamorak13** [comment]
> Padding and font sizes are not set in pixels. They are all set in rem:
> image (nav)
> 
> image
> image
> (ul)
> 
> -> Add it all up:
> ```
> 0.625 (nav top)
> 1.000 (ul top)
> 1.500 (ul line-height)
> 1.000 (up bottom)
> 0.625 (nav bottom)
> -----
> 4.750
> ```
> 
> You can also see that by adding a css rule like
> ```css
> html {
>   font-size: 30px;
> }
> ```
> All the sizes increase, also the pixel size of the header. We have to use rem.

Fair enough. Then you can go ahead an merge. 👍🏼

**Comment by dorianim** [comment]
You have to approve first :)

**Review by lamorak13 — APPROVED** [review]

**Pull request merged**
